name: RSS Everyday
on:
  schedule:
    - cron: '0 */1 * * *'
#env:
#  TZ: Asia/Shanghai

jobs:
    search-and-push:
        runs-on: ubuntu-latest
        steps:
        - name: Install Go
          uses: actions/setup-go@v2
          with:
            go-version: 1.16.x
        - name: Checkout code
          uses: actions/checkout@v2
        - name: build
          run: go run main.go --tg_bot=${{secrets.RSS_TG_BOT_TOKEN}} --tg_channel=${{secrets.RSS_TG_CHANNEL_ID}}
